"""Add asset_type and exchange to Portfolio and Trade

Revision ID: a0bccdb4c949
Revises: 9039d7641087
Create Date: 2025-06-07 21:10:00.829633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0bccdb4c949'
down_revision = '9039d7641087'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asset_symbol', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('asset_type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('exchange', sa.String(length=50), nullable=True))
        batch_op.drop_column('crypto_id')

    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asset_symbol', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('asset_type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('exchange', sa.String(length=50), nullable=True))
        batch_op.drop_column('crypto_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('crypto_id', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('exchange')
        batch_op.drop_column('asset_type')
        batch_op.drop_column('asset_symbol')

    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('crypto_id', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('exchange')
        batch_op.drop_column('asset_type')
        batch_op.drop_column('asset_symbol')

    # ### end Alembic commands ###
