"""Revert stock-related fields from Portfolio and Trade

Revision ID: b58d67d491c5
Revises: a0bccdb4c949
Create Date: 2025-06-07 21:14:55.517068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b58d67d491c5'
down_revision = 'a0bccdb4c949'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted for data preservation ###
    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        # Rename asset_symbol to crypto_id
        batch_op.alter_column('asset_symbol', new_column_name='crypto_id', existing_type=sa.String(length=50), nullable=False)
        # Drop the other columns
        batch_op.drop_column('asset_type')
        batch_op.drop_column('exchange')

    with op.batch_alter_table('trade', schema=None) as batch_op:
        # Rename asset_symbol to crypto_id
        batch_op.alter_column('asset_symbol', new_column_name='crypto_id', existing_type=sa.String(length=50), nullable=False)
        # Drop the other columns
        batch_op.drop_column('asset_type')
        batch_op.drop_column('exchange')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - adjusted for data preservation ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        # Add back columns first
        batch_op.add_column(sa.Column('asset_type', sa.VARCHAR(length=20), nullable=False, server_default='crypto'))
        batch_op.add_column(sa.Column('exchange', sa.VARCHAR(length=50), nullable=True))
        # Rename crypto_id back to asset_symbol
        batch_op.alter_column('crypto_id', new_column_name='asset_symbol', existing_type=sa.String(length=50), nullable=False)


    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        # Add back columns first
        batch_op.add_column(sa.Column('asset_type', sa.VARCHAR(length=20), nullable=False, server_default='crypto'))
        batch_op.add_column(sa.Column('exchange', sa.VARCHAR(length=50), nullable=True))
        # Rename crypto_id back to asset_symbol
        batch_op.alter_column('crypto_id', new_column_name='asset_symbol', existing_type=sa.String(length=50), nullable=False)
    # ### end Alembic commands ###
